package task1;

//imports generated by the IDE
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class Question4 {

    // This method will output a list of multiples of 2
    static void multiplesOf2(List<Integer> myList) {
        System.out.println("The multiples of 2 are :");

        for (int i = 0; i <= myList.size(); i++) {
            if (myList.get(i) % 2 == 0) {
                System.out.println(myList.get(i));

            }
            if (i == 150 - 71) {
                break;
            }
        }
    }

    // This method will output a list of multiples of 3
    static void multiplesOf3(List<Integer> myList) {
        System.out.println("\n\nThe multiples of 3 are :");

        for (int i = 0; i <= myList.size(); i++) {
            if (myList.get(i) % 3 == 0) {
                System.out.println(myList.get(i));

            }
            if (i == 150 - 71) {
                break;
            }

        }
    }

    // This method will output a list of multiples of 7
    static void multiplesOf7(List<Integer> myList) {
        System.out.println("\n\nThe multiples of 7 are :");

        for (int i = 0; i <= myList.size(); i++) {
            if (myList.get(i) % 7 == 0) {
                System.out.println(myList.get(i));

            }
            if (i == 150 - 71) {
                break;
            }

        }
    }

    // main method
    public static void main(String[] args) {

        // This list holds 71-149
        List<Integer> myList = IntStream.range(71, 150).boxed().collect(Collectors.toList());

        // adding last item so that we could also iterate upto 150
        myList.add(150);

        // calling my methods to print the output
        multiplesOf2(myList);
        multiplesOf3(myList);
        multiplesOf7(myList);
    }
}
